name: "Go Code Coverage Report Generator"
description: "Post Go Code Coverage Reports to Pull Requests."
author: "William Juanda"
branding:
  icon: "anchor"
  color: "green"

inputs:
  version:
    description: "The exact version tag to use."
    required: true
    default: "v1.2.0"

  coverage-artifact-name:
    description: 'The name of the artifact containing the code coverage results.'
    required: true
    default: "code-coverage"

  coverage-file-name:
    description: 'The name of the file containing the code coverage results.'
    required: true
    default: "coverage.txt"

  root-package:
    description: |
      The Go import path of the tested repository should be added as a prefix to all paths of the changed files. 
      This is useful for mapping the changed files (e.g., ["foo/my_file.go"]) to their coverage profile, 
      which uses the full package name to identify the files (e.g., github.com/username/example/foo/my_file.go).
      Note that currently, packages with a different name than their directory are not supported.
    required: false
    default: "github.com/${{ github.repository }}"

runs:
  - name: Download go-coverage-report
    id: download
