name: "Go Code Coverage Report Generator"
description: "Post Go Code Coverage Reports to Pull Requests."
author: "William Juanda"
branding:
  icon: "anchor"
  color: "green"

inputs:
  version:
    description: "The exact version tag to use."
    required: true

  coverage-file-name:
    description: 'The name of the file containing the code coverage results.'
    required: true
    default: "coverage.txt"

  root-package:
    description: |
      The Go import path of the tested repository should be added as a prefix to all paths of the changed files. 
      This is useful for mapping the changed files (e.g., ["foo/my_file.go"]) to their coverage profile, 
      which uses the full package name to identify the files (e.g., github.com/username/example/foo/my_file.go).
      Note that currently, packages with a different name than their directory are not supported.
    required: false
    default: "github.com/${{ github.repository }}"

runs:
  using: "composite"

  steps:
    - name: Download go-coverage-report
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/install.sh
      env:
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}

    - name: Determine changed files
      id: changed-files
      uses: tj-actions/changed-files@aa08304bd477b800d468db44fe10f6c61f7f7b11 # v42.1.0
      with:
        write_output_files: true
        json: true
        files: |
          **.go

    - name: Code coverage report
      shell: bash
      id: coverage
      run: $GITHUB_ACTION_PATH/scripts/github-action.sh
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_BASELINE_WORKFLOW_REF: ${{ inputs.github-baseline-workflow-ref }}
        TARGET_BRANCH: ${{ github.base_ref }}
        CHANGED_FILES_PATH: .github/outputs/all_modified_files.json
        COVERAGE_ARTIFACT_NAME: ${{ inputs.coverage-artifact-name }}
        COVERAGE_FILE_NAME: ${{ inputs.coverage-file-name }}
        ROOT_PACKAGE: ${{ inputs.root-package }}
        SKIP_COMMENT: ${{ inputs.skip-comment }}
        TRIM_PACKAGE: ${{ inputs.trim }}
