name: "CI"

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  GO_VERSION: "^1.23"


jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: "Restore Go modules cache"
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Download dependencies"
        run: go mod download

      - name: "Go Test"
        run: go test -cover -coverprofile=coverage.txt -mod=readonly ./...

      - name: "Archive code coverage results"
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.out

  code_coverage:
    name: "Code coverage report"
    runs-on: "ubuntu-latest"
    needs: "tests"
    permissions:
      # Grant permission to add comments to the PR.
      pull-requests: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: ./
        with:
          version: local
